### ISSUE TITLE
configure does not run on Illumos (Tribblix 0m28)

### ISSUE THREAD

**Issue by newmh990** [rdmark/Netatalk-2.x#16]
Issue is related to [https://github.com/rdmark/Netatalk-2.x/issues/13#issue-1341894646](url).  Unable to run the config script on the system with the default configure.ac.  Removed the comments on the lines added for Ubuntu in the linked issue and the config script ran fine.

Output shows as below with the default lines:
`$ ./configure`
`Usage: . [ options ] name [arg ...]`

I checked my autotools binary location and I am using autotools from pkgsrc.
Documenting the issue for building on Illumos.

**Comment by rdmark** [comment]
Thanks for reporting. I'm not really familiar with Illumos, so I must ask what "Tribblix 0m28" means? Is this part of the versioning scheme for the OS?

**Comment by newmh990** [comment]
Tribblix (http://www.tribblix.org/) is a distribution of Illumos.  The number is the versioning scheme for the OS. 0m28 is the latest release.

**Comment by rdmark** [comment]
Well noted. So you're saying that the same workaround that got it working with Ubuntu 18.04 (issue https://github.com/rdmark/Netatalk-2.x/issues/13) also works with Illumos, correct?

This might be a good time to throw up a wiki page or perhaps add this to the README.

**Comment by rdmark** [comment]
Added a paragraph to https://github.com/rdmark/Netatalk-2.x/blob/branch-netatalk-2-x/README.md#feature-configuration-examples

Please let me know if there's anything else that should be called out.

**Comment by newmh990** [comment]
Hello, thank you. This works  for me.
