### ISSUE TITLE
Removal of HAVE_CONFIG_H macro directive causing "missing file" errors building macipgw

### ISSUE THREAD

**Issue by NJRoadfan** [rdmark/Netatalk-2.x#17]
This issue cropped up when testing A2SERVER against newer releases of Netatalk-2.x. Since macipgw is built after the initial netatalk configuration and build, the generated config.h file is missing and will throw a "missing file" error and abort. This applies to any 3rd party programs that link to netatalk's headers as well.

Note that this is not an issue with netatalk-classic since that project folded macipgw into the main netatalk distribution.

This is the commit that removed the macro: https://github.com/christopherkobayashi/netatalk-classic/commit/fd796f7d027fe7aed65872d6b982123428a7ad49

Only the headers in "sys/netatalk" are referenced by macipgw.

**Comment by rdmark** [comment]
@NJRoadfan So reverting the change will restore interoperability with macipgw? Please try this! https://github.com/rdmark/Netatalk-2.x/commit/7280ed020acfce62eeabfbe29d970327b97e5311

**Comment by NJRoadfan** [comment]
That did the trick, macipgw now builds without error.

**Comment by NJRoadfan** [comment]
Hmm, -DHAVE_CONFIG_H might need to be added back to the makefiles. Everything seems to build ok, but config.h is not being processed during normal netatalk builds now.

**Comment by rdmark** [comment]
Do you have an idea what exactly is amiss? I looked at the Makefiles that get generated for me and see `DEFS = -DHAVE_CONFIG_H` consistently, so I'm not sure I'm seeing the same issue as you.

**Comment by NJRoadfan** [comment]
Late night and glancing at yet another build output. Looks ok after a cup of coffee the next morning.
