### ISSUE TITLE
Choose the best default volume icon

### ISSUE THREAD

**Issue by rdmark** [rdmark/Netatalk-2.x#20]
In 2.2, there is [logic ](https://github.com/Netatalk/Netatalk/blob/31843674b7bd32eabcce3a1ad6159b4f94921f79/etc/afpd/icon.h)for choosing a different mounted volume icon depending on certain criteria. I want to pick a default set of icons that are attractive and make sense today.

By default, it will pick an icon that looks similar to Apple's standard AppleShare icon, with slight variations depending on whether it's connected via DDP or DSI (the latter has a little globe icon on the tray as well).

If you turn on the `-icon` option in afpd.conf you get an icon based on platform ifdefs. However, those are all for long deprecated platforms (and the code is actually already removed in 2.x). The platforms and their corresponding icons are:
- `ultrix` (declogo): a DEC logo on a tray
- `vax` (daemon): what looks like the BSD demon mascot head on a tray -- I assume the Netatalk authors ran a BSD flavor on the VAXStations?
- `sun` (sunlogo): a Sun logo on a tray
- `_IBMR2` (hagar): what looks like the head of a penguin wearing a horned helmet on a tray -- Hagar refers to the cartoon character. I am guessing IBMR2 refers to a flavor of AIX. Anyone knows the history behind this one? Was this an unofficial mascot for AIX?
- the `#else` fallback (globe): a globe on a tray -- so boring!

I personally really like hagar and daemon. The daemon on a tray is the traditional mascot for Netatalk, and you can actually see his silhouette in the present-day [Netatalk logo](https://netatalk.sourceforge.io).

![netatalk-icons](https://user-images.githubusercontent.com/2108467/212229579-6ef44773-5655-487e-9c7f-9e7c5e335b18.png)

**Comment by rdmark** [comment]
@NJRoadfan I'd love to get your stylistic opinion here.

My immediate thought is to keep the default behavior of files-on-a-tray, with a distinction between DDP and DSI connections. This is marginally useful to have. And then have "daemon" as the one you always get with the `-icon` option.

Alternatively, introduce ifdefs for Linux and BSD flavors, and use "hagar" with the former (because it looks like Tux with a helmet!) and "daemon" for the latter.

A third option would be to use "daemon" all the time.

At the same time, Hagar looks kind of neat so I would hate to discard him.

Thoughts?

**Comment by rdmark** [comment]
Here is what they look like in context.

![beastie](https://user-images.githubusercontent.com/2108467/212230457-e10bce67-0ea8-4255-b50c-d06eee4f6bb2.png)
![hagar](https://user-images.githubusercontent.com/2108467/212230459-86376749-15a5-4265-9b27-71f691920c12.png)

**Comment by NJRoadfan** [comment]
I rarely see the actual icon the server gives out. MacOS 8.0 and newer use a built-in color icon and GS/OS uses its own as well.

**Comment by rdmark** [comment]
Are you sure about Mac OS 8.0? I'm using 9.1 one on another Mac here and definitely seeing the custom 1 bit icons that Netatalk is serving.

Have you tried applying the `-icon` option and see if that makes a difference?

**Comment by rdmark** [comment]
I could confirm: When applying the `-noicon` option, or nothing at all, Mac OS 9.1 will fall back to its own color icon.

**Comment by NJRoadfan** [comment]
This is weird. In testing, a MacOS 8.1 install in Basilisk II refuses to show the custom icon. Meanwhile the custom icon works fine under a 9.0.4 install. Naturally System 7.1 works fine.

**Comment by rdmark** [comment]
Conveniently, asip-status.pl can tell you the icon that the DSI server is serving with the -i option:

```
$ ./asip-status.pl -i localhost
AFP reply from localhost:548 via IPv6
Flags: 1  Cmd: 3  ID: 57005
Reply: DSIGetStatus
Request ID: 57005
Machine type: Netatalk2.221101
AFP versions: AFP2.2,AFPX03,AFP3.1,AFP3.2,AFP3.3
UAMs: DHX2,Cleartxt Passwrd
Volume Icon & Mask: Yes
Flags:
    SupportsCopyFile
    SupportsServerMessages
    SupportsServerSignature
    SupportsTCP/IP
    SupportsSrvrNotifications
    SupportsOpenDirectory
    SupportsUTF8Servername
    SupportsUUIDs
    SupportsExtSleep
    SupportsSuperClient
Server name: rasp32
Signature:
e3 62 66 65 ca eb 04 cd ab 65 be e0 9c 06 6c 82  .bfe.....e....l.

Network address: 10.0.0.242 (IPv4 address)
UTF8 Servername: rasp32

        #             #
       ##             ##
      # #             # #
      # #             # #
     #  #             #  #
     #  #    #####    #  #
     #   # ##     ## #   #
     #    #         #    #
      #    # ## ## #    #
       #       #       #
      # #             # #
      # #  ###   ###  # #
     #    #   # #   #    #
     #   #     #     #   #
     #   #     #     #   #
     #   #     #     #   #
     #   #  #  #  #  #   #
    ###  # # # # # # #  ###
   #     # ### # ### #     #
   #      ##### #####      #
 #############   ##############
  #          #   #           #
   ###########   ############
             #####
             #   #
              ###
             #   #
# # #########  #  ########## # #
              # #
# # ##########   ########### # #


```

**Comment by rdmark** [comment]
I went with option #1 -- Daemon is now the default for the `-icon` setting. Turns out the upstream project did the same change in 3.x a decade ago https://github.com/Netatalk/Netatalk/commit/507493b4e4bd5be7a951b800644222ad00678d7c
