### ISSUE TITLE
asip-status.pl script is broken

### ISSUE THREAD

**Issue by NJRoadfan** [rdmark/Netatalk-2.x#21]
The @PERL@ and @NETATALK_VERSION@ placeholders are no longer being replaced with proper values during build.

**Comment by rdmark** [comment]
The first one is probably due to https://github.com/rdmark/Netatalk-2.x/commit/c99d23bbfafb939438d4d4a02c7dc85a2648c2e8

When Chris K rewrote `macusers` as a shell script he forgot to check that there weren't any other Perl script in the repo (and I didn't validate it myself either.)

**Comment by rdmark** [comment]
Pushed fixes for both issues. Please test!

**Comment by rdmark** [comment]
The script works for me. Handy script! I didn't know about it. Netatalk has such a ridiculous amount of utility.

**Comment by rdmark** [comment]
In fact, I found that the script has gotten a bunch of improvements in upstream master. I merged those improvements here.

**Comment by NJRoadfan** [comment]
Tested and working again. IPv6 support appears to work as well.
