### ISSUE TITLE
Building 2.2 on 64bit raspberry pi OS

### ISSUE THREAD

**Issue by ShadeDream** [rdmark/Netatalk-2.x#3]
Tried compiling and installing on a fresh install of 64 bit raspberry pi OS. Maybe I jumped the gun a little by jumping over to the new 64 bit OS...

Ran `bootstrap` then configured with the example given over on 68kmla.

```
./configure --enable-systemd --enable-ddp --enable-a2boot --enable-cups --enable-timelord --disable-zeroconf --disable-quota --sysconfdir=/etc --with-uams-path=/usr/lib/netatalk
```

When running `make` the following error occurs:

```
Making all in afpd
make[3]: Entering directory '/home/shade/source/Netatalk-2.x/etc/afpd'
gcc -DHAVE_CONFIG_H -I. -I../..    -DKAZLIB_TEST_MAIN -I../../include -I../../include -D_U_="__attribute__((unused))" -g -O2 -I../../sys -MT hash-hash.o -MD -MP -MF .deps/hash-hash.Tpo -c -o hash-hash.o `test -f 'hash.c' || echo './'`hash.c
mv -f .deps/hash-hash.Tpo .deps/hash-hash.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -DKAZLIB_TEST_MAIN -I../../include -I../../include -D_U_="__attribute__((unused))" -g -O2 -I../../sys   -o hash hash-hash.o  -lpthread  -L../../libatalk
libtool: link: gcc -DKAZLIB_TEST_MAIN -I../../include -I../../include "-D_U_=__attribute__((unused))" -g -O2 -I../../sys -o hash hash-hash.o  -lpthread -L../../libatalk
gcc -DHAVE_CONFIG_H -I. -I../..    -DFCE_TEST_MAIN -I../../include -I../../include -D_U_="__attribute__((unused))" -g -O2 -I../../sys -MT fce-fce_api.o -MD -MP -MF .deps/fce-fce_api.Tpo -c -o fce-fce_api.o `test -f 'fce_api.c' || echo './'`fce_api.c
mv -f .deps/fce-fce_api.Tpo .deps/fce-fce_api.Po
gcc -DHAVE_CONFIG_H -I. -I../..    -DFCE_TEST_MAIN -I../../include -I../../include -D_U_="__attribute__((unused))" -g -O2 -I../../sys -MT fce-fce_util.o -MD -MP -MF .deps/fce-fce_util.Tpo -c -o fce-fce_util.o `test -f 'fce_util.c' || echo './'`fce_util.c
mv -f .deps/fce-fce_util.Tpo .deps/fce-fce_util.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -DFCE_TEST_MAIN -I../../include -I../../include -D_U_="__attribute__((unused))" -g -O2 -I../../sys   -o fce fce-fce_api.o fce-fce_util.o ../../libatalk/libatalk.la -lpthread  -L../../libatalk
libtool: link: gcc -DFCE_TEST_MAIN -I../../include -I../../include "-D_U_=__attribute__((unused))" -g -O2 -I../../sys -o fce fce-fce_api.o fce-fce_util.o  ../../libatalk/.libs/libatalk.a -L../../libatalk -L../libatalk -lpthread
/usr/bin/ld: fce-fce_util.o:/home/shade/source/Netatalk-2.x/etc/afpd/directory.h:96: multiple definition of `invalid_dircache_entries'; fce-fce_api.o:/home/shade/source/Netatalk-2.x/etc/afpd/directory.h:96: first defined here
/usr/bin/ld: fce-fce_util.o:/home/shade/source/Netatalk-2.x/etc/afpd/volume.h:39: multiple definition of `current_vol'; fce-fce_api.o:/home/shade/source/Netatalk-2.x/etc/afpd/volume.h:39: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:590: fce] Error 1
make[3]: Leaving directory '/home/shade/source/Netatalk-2.x/etc/afpd'
make[2]: *** [Makefile:444: all-recursive] Error 1
make[2]: Leaving directory '/home/shade/source/Netatalk-2.x/etc'
make[1]: *** [Makefile:496: all-recursive] Error 1
make[1]: Leaving directory '/home/shade/source/Netatalk-2.x'
make: *** [Makefile:426: all] Error 2
```

**Comment by rdmark** [comment]
@ShadeDream This is an odd one, because those look exactly like the errors that should have been suppressed with this commit: https://github.com/rdmark/Netatalk-2.x/commit/d9ff3b8b516aaee8a270919d3d4894bf81bf7d61

Can you please double check which GIt branch you are on? You should be using ``` branch-netatalk-2-x ```

**Comment by ShadeDream** [comment]
Ahh that's quite possible. I don't have the details up in front of me right now, but the instructions I read said to check out the `branch-netatalk-2-2` branch instead (which seemed odd, but I went with it). I'll try to get back to it and give it a shot tomorrow and see if that resolves the issue.

**Comment by rdmark** [comment]
This is most certainly the problem here, then! The ``` branch-netatalk-2-2 ``` branch is an exact copy of the upstream codebase, so it shares all the issues that I have addressed in ``` branch-netatalk-2-x ```. I've kept this arrangement in order to easily create clean PRs against upstream Netatalk, although the drawback is that it may lead to mistakes like this...

**Comment by ShadeDream** [comment]
Switched back over to the `branch-netatalk-2-x` branch and it compiled successfully on my Pi 4 with 64bit OS. Just testing it fast in the background at the moment and haven't had a chance to set it up and connect, but since it's building successfully, I'm back on the correct track.

I think where I got off track is that in the initial post over on 68kmla it mentions a `branch-netatalk-2-2-x` branch which seems ambiguous or a branch that no longer exists and I must have interpreted that as needing to check out `branch-netatalk-2-2`. Might be worth updating that post if possible.

**Comment by rdmark** [comment]
That's encouraging! Yes, if it compiles without warnings I don't think 32bit vs 64bit should matter anymore.

Unfortunately, 68kmla doesn't allow you to edit posts that are older than an few hours. I've pinged admin staff to see if it can be done.

**Comment by rdmark** [comment]
Admins helped me fix the 68kmla post: https://68kmla.org/bb/index.php?threads/yet-another-netatalk-2-2-fork.39889/
Thanks for raising the issue!
