### ISSUE TITLE
[papd] CUPS PPD API Deprecation

### ISSUE THREAD

**Issue by NJRoadfan** [rdmark/Netatalk-2.x#31]
Right now papd uses the long deprecated CUPS PPD API to grab the current printer's PPD for its own use. Starting with CUPS 3.0, this API is going away as CUPS will no longer support printer drivers using that architecture. PPD files are not critical to papd's functioning. It is primarily used as a way to source responses to queries from clients regarding printer capabilities (printer name, color support, etc.).

One possible solution is to generate a "stub" PPD on the fly using IPP queries of the currently selected printer. This approach is already used by CUPS to support "driverless" printers behind-the-scenes, but is going away in 3.0 as well.

**Comment by rdmark** [comment]
@NJRoadfan Are you ready to port this to upstream netatalk2 soon-ish? I was planning to cut a release soon after since we have a good chunk of fixes in the branch.

**Comment by NJRoadfan** [comment]
There are some extra refinements I want to make to the PPD parsing code to deal with the LaserWriter 8 driver's resolution query. Right now they don't work...... well they never worked.

**Comment by NJRoadfan** [comment]
Done. See #37.

**Comment by rdmark** [comment]
Cheers! I merged the PR. Didn't actually dynamically test it in my environment yet but I'll get to it tomorrow.
