### ISSUE TITLE
TimeLord is not working with atalkd in router mode

### ISSUE THREAD

**Issue by NJRoadfan** [rdmark/Netatalk-2.x#39]
Any attempts to use the tardis application on a client Macintosh results in a "ding" and the time is not synced with the server.

Client: Quadra 605 running System 7.1 and tardis 1.6. tardis 1.3 was also tested.

Server: netatalk-2.x tested on both a x86_64 VM and ARM RPi 400. Both are running the latest patches for Debian 11/bullseye.

**Comment by NJRoadfan** [comment]
Figured out the problem. The tardis extension doesn't seem to like working in an AppleTalk zone for some reason. Turning off atalkd's router functionality allows tardis to sync the clock.

**Comment by rdmark** [comment]
Huh, that's an unexpected limitation/bug. Too bad we don't have the source code for tardis to fix it.

And you're sure netatalk's timelord itself isn't to blame? Does a2boot work with zones (it is based on timelord code)?

**Comment by NJRoadfan** [comment]
a2boot works fine. Heck, when I boot my Apple IIgs over the network, its on a separate network number and zone. I did further testing using my Shiva Fastpath 5 as a router, and it fails there too. So that rules out atalkd as the source of the problem. I also tried out syncing the clock to the original TimeLord CDEV, and it isn't working either. I suspect it is a tardis bug at this point.

Running Wireshark, I'm not seeing any ATP packets from timelord or tardis over the network. Just normal NBP packets from Chooser while it is open. This seems like a really obvious bug, particularly if Timelord was ever used on a medium/large sized network.

**Comment by rdmark** [comment]
That's so strange, given that tardis/timelord was developed at the University of Melbourne which must certainly have had an appletalk network with significant complexity up and running at one point... Or maybe they had one timelord server per zone or something...?

**Comment by NJRoadfan** [comment]
The original TimeLord server for CAP is here: https://github.com/mabam/CAP/tree/master/contrib/Timelord

The code does handle NBP registration with zones.

**Comment by rdmark** [comment]
@NJRoadfan if you think netatalk's timelord can be improved to work around this suspected tardis bug, please file an issue with the mother project.

I would have migrated the issue over there if GitHub allowed it, but alas that is not possible. (https://github.com/orgs/community/discussions/4480)
