### ISSUE TITLE
Revised bootstrap checks require package "libtool-bin" on Debian 12.

### ISSUE THREAD

**Issue by NJRoadfan** [rdmark/Netatalk-2.x#40]
As above. Installing package "libtool" isn't enough anymore. The actual libtool command requires package "libtool-bin" to be installed on Debian 12 systems, otherwise the bootstrap script will exit complaining about libtool not being installed. This may also be the case on other distributions as well.

Suggest revising documentation to install "libtool-bin" vs. "libtool"

**Comment by rdmark** [comment]
Well noted. I did capture this requirement in the wiki here: https://github.com/Netatalk/netatalk/wiki/Installation-Notes#debian-linux

Is there anywhere else where the documentation should be updated, you think?

I *think* this is a Debian specific requirement. Fedora, SuSE, Alpine etc. install the requisite binaries through their corresponding `libtool` package. Same goes for FreeBSD, OmniOS, OpenIndiana...

**Comment by NJRoadfan** [comment]
README.md needs to be updated. I have been testing bookworm now that it is out with a2server and ran across this problem building the latest tree. Everything else seems to be working outside of the DHX UAM thanks to the new OpenSSL dropping support for 128bit ciphers. (As noted on the main Netatalk issues list).

**Comment by rdmark** [comment]
Good call. Updated the readme with https://github.com/rdmark/netatalk-2.x/commit/69967487ad1581e1528c6e704833ac95ffc95a95
