### ISSUE TITLE
Can't compile Netatalk-2.x on RPi3b

### ISSUE THREAD

**Issue by Deftaudio** [rdmark/Netatalk-2.x#6]
Please, suggest. I'm having hard times to compile netatalk-2.x. It stops on RPi3 with the following error:
```
Making all in initscripts
make[3]: Entering directory '/home/pi/Netatalk-2.x/distrib/initscripts'
make[3]: *** No rule to make target 'a2boot.service', needed by 'all-am'.  Stop.
make[3]: Leaving directory '/home/pi/Netatalk-2.x/distrib/initscripts'
make[2]: *** [Makefile:426: all-recursive] Error 1
make[2]: Leaving directory '/home/pi/Netatalk-2.x/distrib'
make[1]: *** [Makefile:479: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/Netatalk-2.x'
make: *** [Makefile:409: all] Error 2
```
I'm using basic config:
```
$ ./bootstrap
$ ./configure --enable-systemd --enable-zeroconf
$ make
```

**Comment by rdmark** [comment]
@Deftaudio I assume you're using the stable v220101 release?

If you don't mind, can you please try the latest development code in branch-netatalk-2-x? I've simplified the configure script and Makefiles so that a2boot and other daemons are always compiled and always installed. Before there was a rat's nest of conditionals prone to failure.

**Comment by Deftaudio** [comment]
I'm sorry for not specifying a version. No, actually, I was trying on the latest branch. But as you mentioned some changes in Makefile I went backwards and cloned `netatalk-2-220101` tag. 
Then I compiled it successfully following by rascsi instruction:
```
$ ./bootstrap
$ ./configure --enable-systemd --enable-ddp --enable-a2boot --enable-cups --enable-timelord --enable-zeroconf --sysconfdir=/etc --with-uams-path=/usr/lib/netatalk
$ make all
$ sudo make install
```

**Comment by rdmark** [comment]
@Deftaudio This commit should resolve the issue on branch-netatalk-2-x! https://github.com/rdmark/Netatalk-2.x/commit/f37dba44e4cb770323179ba993fd3c26cd28a088

Would you have a few minutes to test it in your environment? For proper testing, please make sure the generated *.service files have been deleted from distrib/initscripts/ first, either by a make clean, manual deletion, etc.

**Comment by Deftaudio** [comment]
Thank you, I tested this commit. It works fine.

**Comment by rdmark** [comment]
Thanks for reporting, and testing!
